
#base
server:
  port: 8080
spring:
  data:
   mongodb:
    database: roottest
    host: 127.0.0.1
    port: 27017
  application:
    name: springboot-elasticsearch-example

#elasticsearch
elasticsearch:
  schema: http
  address: 192.168.226.128:9200
  connectTimeout: 5000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100
